apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-database-authentication
  namespace: platform
spec:
  refreshInterval: 5m
  secretStoreRef: {name: {{ .Values.secretStore }}, kind: ClusterSecretStore}
  target: {name: backstage-database-authentication}
  data:
    - secretKey: POSTGRES_USER
      remoteRef: {key: backstage, property: postgres-user}
    - secretKey: POSTGRES_PASSWORD
      remoteRef: {key: backstage, property: postgres-password}
    - secretKey: POSTGRES_PORT
      remoteRef: {key: backstage, property: postgres-port}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-db
  namespace: platform
spec:
  refreshInterval: 5m
  secretStoreRef: {name: {{ .Values.secretStore }}, kind: ClusterSecretStore}
  target: {name: backstage-db}
  data:
    - secretKey: postgres-password
      remoteRef: {key: backstage, property: postgres-password}
    - secretKey: password
      remoteRef: {key: backstage, property: postgres-password}
    - secretKey: user-password
      remoteRef: {key: backstage, property: postgres-password}
    - secretKey: admin-password
      remoteRef: {key: backstage, property: postgres-password}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-github-authentication
  namespace: platform
spec:
  refreshInterval: 5m
  secretStoreRef: {name: {{ .Values.secretStore }}, kind: ClusterSecretStore}
  target: {name: backstage-github-authentication}
  data:
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef: {key: backstage, property: github-client-id}
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef: {key: backstage, property: github-client-secret}
    - secretKey: GITHUB_APP_ID
      remoteRef: {key: backstage, property: github-app-id}
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef: {key: backstage, property: github-app-private-key}
    - secretKey: GITHUB_APP_WEBHOOK_SECRET
      remoteRef: {key: backstage, property: github-app-webhook-secret}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-kubernetes-authentication
  namespace: platform
spec:
  refreshInterval: 5m
  secretStoreRef: {name: {{ .Values.secretStore }}, kind: ClusterSecretStore}
  target: {name: backstage-kubernetes-authentication}
  data:
    - secretKey: K8S_TOKEN
      remoteRef: {key: backstage, property: kubernetes-tooling-token}
    - secretKey: K8S_URL
      remoteRef: {key: backstage, property: kubernetes-tooling-url}
