# Global configuration for all applications
#
parent: false
env: non-prod
project: controller

source:
  server: https://kubernetes.default.svc
  namespace: argocd


destination:
  server: https://kubernetes.default.svc
  namespace: controller

