# Global configuration for all applications
# This values file will only create parent applications
parent: true

global:
  defaultCluster: https://kubernetes.default.svc
  namespace: cd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false


applications:
  controller-applications:
    name: controller-applications
    description: deploy argocd applications
    project: deploy
    source:
      repoURL: git@github.com:polarpoint-io/argocd-controller-applications.git
      path: releases
      targetRevision: main
      valuesFile: "global-values-non-prod.yaml"

